Move all to getters
bem-sdk/bem-bundle pull request #8
Opened 2016-08-18 18:25 UTC by skad0

Solve #5 
All properties calculation moved to getters

2016-08-19 11:34 UTC, zxqfox commented on lib/index.js
> +        this._opts.name = this._opts.name || path.basename(this._opts.path).split('.')[0];
`return this._var || (this._var = ...);`?

2016-09-20 06:22 UTC, skad0 commented
/cc @zxqfox @blond @tadatuta

2016-09-20 17:58 UTC, zxqfox commented on lib/index.js
> +        return this._opts.decl || (bemjsonToDecl.convert(this._opts.bemjson));
скобки лишние?

2016-09-20 18:08 UTC, zxqfox commented on lib/index.js
> +        return this._opts.decl || (bemjsonToDecl.convert(this._opts.bemjson));
тут забыто `this._opts.decl = `

2016-09-20 18:08 UTC, qfox requested changes

2016-09-20 19:02 UTC, blond requested changes
Хорошо бы кэшировать вычисления.

2016-09-20 19:06 UTC, qfox approved these changes

2016-09-20 19:06 UTC, zxqfox commented
> Хорошо бы кэшировать вычисления.

Что именно кешировать?

2016-09-21 09:52 UTC, blond commented
> Что именно кешировать?

Оказывается, уже ничего.

2016-09-21 09:52 UTC, blond approved these changes

2016-09-21 10:01 UTC, merged